#manifest 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
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}-deployment
spec:
  selector:
    matchLabels:
      app: {model_name}-server
  replicas: 1
  template:
    metadata:
      labels:
        app: {model_name}-server
    spec:
      containers:
      - name: {model_name}-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/ivanavila/fastapiml:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {model_name}-service
  name: {model_name}-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {model_name}-server
  type: LoadBalancer